In [63]:
import numpy as np

x_array = np.arange(1,11, 2)
# 可以使用“command+/”快速将某一行变成注释行，或者取消注释
print(x_array)

[1 3 5 7 9]


In [64]:
greeting_str = "Hey, Jack!"
# 使用enumerate函数，可以同时获取索引和值
for index, char in enumerate(greeting_str, start=0):
    print(f"字符：{char}，索引：{index}")

字符：H，索引：0
字符：e，索引：1
字符：y，索引：2
字符：,，索引：3
字符： ，索引：4
字符：J，索引：5
字符：a，索引：6
字符：c，索引：7
字符：k，索引：8
字符：!，索引：9


快速把单元格光标处分裂成两格单元格的快捷键“control + shift + -”

In [65]:
# enumerate函数：将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，
# 同时列出数据和数据下标，一般用在 for 循环当中，例如👇
import random
ls = [random.randint(1, 101) for i in range(10)]
print(ls)
for index, value in enumerate(ls, start=1):
    print(f"第{index}个元素是：{value}")

[84, 28, 60, 75, 85, 79, 85, 48, 93, 5]
第1个元素是：84
第2个元素是：28
第3个元素是：60
第4个元素是：75
第5个元素是：85
第6个元素是：79
第7个元素是：85
第8个元素是：48
第9个元素是：93
第10个元素是：5


In [66]:
a = [[0, 5],
     [3, 4],
     [5, 0]]
# 取出行向量
for i in range(3):
    print(a[i])
# 取出列向量
print([row[0] for row in a])
print([row[1] for row in a])

[0, 5]
[3, 4]
[5, 0]
[0, 3, 5]
[5, 4, 0]


鸢尾花数据集：是一种经典的用于机器学习和模式识别的数据集。由统计学家罗纳德·费舍尔 (Ronald Fisher) 在1936 年引入，并被广泛用于模式识别和机器学习的教学和研究。是机器学习领域的一个基准测试数据集，被用来评估分类算法的性能。加载方法如下：

In [67]:
from sklearn.datasets import load_iris
iris = load_iris()
# 特征数据
print(iris.data) 
# 标签
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

数据集简介:

	•	样本数量：150个数据样本。

	•	类别：分为三种鸢尾花品种，每类50个样本：

		•	山鸢尾（Iris-Setosa）
		•	变色鸢尾（Iris-Versicolour）
		•	维吉尼亚鸢尾（Iris-Virginica）

	•	特征数量：4个数值型特征，单位为厘米：
		•	萼片长度（Sepal Length）
		•	萼片宽度（Sepal Width）
		•	花瓣长度（Petal Length）
		•	花瓣宽度（Petal Width）

In [68]:
# 使用pandas库导入Iris数据
import pandas as pd
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
print(iris.head())

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa


In [69]:
# 综合方法，使用sklearn库导入Iris数据，然后转换成pandas数据框
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df_data = pd.DataFrame(iris.data, columns=iris.feature_names)
df_data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [70]:
df_target = pd.DataFrame(iris.target, columns=['target'])
df_target.head()

target
0       0
1       0
2       0
3       0
4       0

In [71]:
# 关于itertools.combinations()函数的用法
import itertools
# 生成所有可能的组合（非重复组合），其中第一个参数是要进行组合的元素列表，第二个参数是组合的元素个数
combinations = itertools.combinations([1, 2, 3, 4], 2)
for combination in combinations:
    print(combination)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [72]:
# 生成所有可能的组合（重复组合），其中第一个参数是要进行组合的元素列表，第二个参数是组合的元素个数
combinations = itertools.combinations_with_replacement([1, 2, 3, 4], 2)
for combination in combinations:
    print(combination)

(1, 1)
(1, 2)
(1, 3)
(1, 4)
(2, 2)
(2, 3)
(2, 4)
(3, 3)
(3, 4)
(4, 4)


In [73]:
# 生成指定序列中元素的所有排列
permutations = itertools.permutations([1, 2, 3, 4], 2)
for permutation in permutations:
    print(permutation)

(1, 2)
(1, 3)
(1, 4)
(2, 1)
(2, 3)
(2, 4)
(3, 1)
(3, 2)
(3, 4)
(4, 1)
(4, 2)
(4, 3)


In [74]:
# 计算两个向量的内积（点积）
a = [i for i in range(1, 6)]
b = [i for i in range(6, 11)]

In [75]:

# 初始化内积为0
dot_product = 0

# 计算内积
for i in range(len(a)):
    dot_product += a[i] * b[i]

print(dot_product)

130


In [76]:
# 计算两个向量的外积（叉积）
a = [1, 2, 3]
b = [4, 5, 6]

# 初始化外积为0 
outer_product = np.zeros((len(a), len(b)))

# 计算外积
for i in range(len(a)):
    for j in range(len(b)):
        outer_product[i][j] = a[i] * b[j]

print(outer_product)

[[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]]


zip()的用法

In [ ]:
names = ['Alice', 'Bob', 'Charlie']
ages = [25, 30, 35]

# 使用zip()函数将两个列表组合成一个元组列表
for name, age in zip(names, ages):
    print(f"{name} is {age} years old.")

Alice is 25 years old.
Bob is 30 years old.
Charlie is 35 years old.


两个矩阵的乘法

In [82]:
a = [[1, 2, 10, 20],
     [3, 4, 30, 40],
     [5, 6, 50, 60]]
b = [[4, 2],
     [3, 1],
     [40, 20],
     [30, 10]]
# c变量用来存法结果
c = [[0, 0],
     [0, 0],
     [0, 0]]

In [83]:
for i in range(len(a)):
    for j in range(len(b[0])): 
        for k in range(len(b)): 
            c[i][j] += a[i][k] * b[k][j]
for row in c:
    print(row)

[1010, 404]
[2424, 1010]
[3838, 1616]


In [84]:
# 矩阵乘法
a = np.array(a)
b = np.array(b)

# 使用numpy的dot()函数计算矩阵乘法
result = np.dot(a, b)
print(result)

[[1010  404]
 [2424 1010]
 [3838 1616]]


In [85]:
result = a @ b
print(result)

[[1010  404]
 [2424 1010]
 [3838 1616]]


列表生成式(list comprehension)的用法

In [87]:
# 生成一个包含1到10的平方的列表
squares = [x**2 for x in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [89]:
# 列表生成式的嵌套用法
matrix = [[i*j for j in range(1,4)] for i in range(1, 4)]
print(matrix)

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [90]:
even_nums = [x for x in range(1, 11) if x % 2 == 0]
print(even_nums)

[2, 4, 6, 8, 10]


Exercises:

In [ ]:
class Solution:
    # 输入一个数字并将其转换为整数，如果输入的不是数字，则提示用户重新输入直到输入数字为止。
    def is_num(self):
        while True:
            num = input("请输入一个数字：")
            try:
                num = int(num)
                print(f"您输入的整数是：{num}")
                break
            except ValueError:
                print("输入的不是整数，请重新输入！")
    # 求100以内的素数。
    def is_prime(self, n):
        if n <= 1:
            return False
        for i in range(2, int(n**0.5)+1):
            if n % i == 0:
                return False
        return True
    # 请用至少两种不同办法计算 1-100 中奇数之和。
    def sum_odd1(self, n):
        return sum(x for x in range(1, n+1) if x % 2 == 1)
    def sum_odd2(self, n):
        return sum(x for x in range(1, n+1, 2))
    def sum_odd3(self, n):
        total = sum(x for x in range(1, n+1))
        return total//2 - (n//4)
    # 写两个函数分别计算矩阵行、列方向元素之和。
    def sum_row(self, matrix):
        row_sums = []        
        for i in range(len(matrix)):
            temp = 0
            for j in range(len(matrix[i])):
                temp += matrix[i][j]
            row_sums.append(temp)
        return sum(row_sums)
    def sum_col(self, matrix):
        col_sums = []
        for i in range(len(matrix[0])):
            temp = 0
            for j in range(len(matrix)):
                temp += matrix[j][i]
            col_sums.append(temp)
        return sum(col_sums)

In [128]:
if __name__ == "__main__":
    s = Solution()
    s.is_num()

输入的不是整数，请重新输入！
您输入的整数是：45


In [129]:
if __name__ == "__main__":
    s = Solution()
    prime_nums = [x for x in range(2, 101) if s.is_prime(x)]
    print(prime_nums)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [140]:
if __name__ == "__main__":
    s = Solution()
    print(s.sum_odd1(10))
    print(s.sum_odd2(10))
    print(s.sum_odd3(10))

25
25
25


In [148]:
ls = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]]
if __name__ == "__main__":
    s = Solution()
    print(s.sum_row(ls))
    print(s.sum_col(ls))

78
78


$2 \times 2矩阵\boldsymbol {A} = \begin{bmatrix} a & b \\
c & d \end{bmatrix}的逆为\frac {1}{ad-bc}\begin{bmatrix} d & -b \\
-c & a \end{bmatrix}。$